/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.panzercraft.gui.editor;

import static de.panzercraft.main.ArduinoProgrammer.VERSION;
import jaddon.controller.JFrameManager;
import jaddon.controller.StaticStandard;
import java.awt.Component;
import java.awt.Dimension;
import java.util.ArrayList;

/**
 *
 * @author Paul
 */
public class Editor extends JFrameManager {
    
    private final ArrayList<EditorTab> editortabs = new ArrayList<>();
    private int pre_work_title = -1;

    /**
     * Creates new form Editor
     * @param title String title
     */
    public Editor(Component c, String title) {
        super(title, VERSION);
        initComponents();
        init(c);
    }
    
    private void init(Component c) {
        setSize(new Dimension(600, 400));
        pack();
        setLocationRelativeTo(c);
        updateAll();
    }
    
    public EditorTab addTab(String name) {
        try {
            EditorTab editortab = new EditorTab(this, name);
            editortabs.add(editortab);
            editortab.add();
            updateAll();
            return editortab;
        } catch (Exception ex) {
            updateAll();
            StaticStandard.logErr("Error while adding tab to editor: " + ex, ex);
            return null;
        }
    }
    
    public EditorTab getSelectedEditorTab() {
        try {
            for(EditorTab editortab : editortabs) {
                if(tabbedpane.getTitleAt(tabbedpane.getSelectedIndex()).equals(editortab.getName())) {
                    return editortab;
                }
            }
            return null;
        } catch (Exception ex) {
            return null;
        }
    }

    public void updateAll() {
        try {
            try {
                delPreWork(pre_work_title);
                pre_work_title = addPreWork(getSelectedEditorTab().getName());
            } catch (Exception ex) {
                delPreWork(pre_work_title);
            }
        } catch (Exception ex) {
            StaticStandard.logErr("Error while updating editor: " + ex, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedpane = new javax.swing.JTabbedPane();
        menubar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().add(tabbedpane, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        menubar.add(jMenu1);

        jMenu2.setText("Edit");
        menubar.add(jMenu2);

        setJMenuBar(menubar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor(null, "Test").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    public javax.swing.JMenuBar menubar;
    public javax.swing.JTabbedPane tabbedpane;
    // End of variables declaration//GEN-END:variables
}
